import { choice } from "@typesafe-ai/sdk";

/** The emojis Jev picks from to celebrate a question, each with what it stands for. */
const EMOJIS: Record<string, string> = {
  "🍕": "pizza, Italian food",
  "🍜": "noodles, ramen, Asian food",
  "🌮": "tacos, Mexican food",
  "🍣": "sushi, Japanese food",
  "🥐": "bread, pastry, bakery",
  "🧀": "cheese, dairy",
  "🍷": "wine, vineyards",
  "🍺": "beer, pubs, drinking",
  "☕": "coffee, tea, cafés",
  "🌶️": "spicy food, chili",
  "🍫": "chocolate, sweets, desserts",
  "⚽": "football, soccer",
  "🏀": "basketball, American sports",
  "🏏": "cricket",
  "⛷️": "skiing, winter sports, snow",
  "🏄": "surfing, beaches, waves",
  "💃": "dance, tango, salsa, flamenco",
  "🎵": "music, songs, musicians",
  "🎬": "film, cinema, TV",
  "📚": "books, literature, writers",
  "🎨": "art, painting, museums",
  "🏛️": "history, ancient civilizations, monuments",
  "⚔️": "war, battles, conflict",
  "👑": "royalty, monarchy, empires",
  "🗳️": "politics, government, elections",
  "🕌": "religion, faith, temples",
  "🗣️": "languages, speaking",
  "💰": "money, economy, wealth, trade",
  "💻": "technology, computers, startups",
  "🚀": "space, rockets, science",
  "🛢️": "oil, energy, fuel",
  "🌋": "volcanoes, earthquakes",
  "🏔️": "mountains, hiking",
  "🏝️": "islands, tropics, holidays",
  "🏜️": "deserts, heat, sand",
  "🌲": "forests, nature",
  "❄️": "cold, ice, the Arctic",
  "🌌": "northern lights, night sky, stars",
  "🌊": "sea, ocean, fjords, rivers",
  "🐘": "wildlife, safari, animals",
  "🐟": "fish, fishing, seafood",
  "🌸": "flowers, spring, gardens",
  "🌾": "farming, agriculture, crops",
  "🏙️": "cities, skyscrapers, urban life",
  "✈️": "travel, tourism",
  "🚗": "cars, driving, roads",
  "🎉": "festivals, parties, celebrations",
  "❤️": "love, romance",
  "😂": "jokes, humor, fun",
  "🌍": "anything else, the world in general",
};

export const emojiQuestion = choice("Which emoji best captures `query`?", EMOJIS);
